
package Model;

import javax.media.j3d.Canvas3D;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class PanelControl extends javax.swing.JFrame {

    private Universo universe;

    public PanelControl(Canvas3D canvas, Canvas3D canvasVariable, Universo anUniverse) {
        super();
        universe = anUniverse;
        initComponents();
        setLocation (915, 338);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                closeApp(0);
            }
        });
        Ventana ventana = new Ventana (this, false, canvas, 915, 0);
        ventana.setVisible(true);
        Ventana visualizationVariable = new Ventana (this, false, canvasVariable, 0, 0);
        visualizationVariable.setVisible(true);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        camaraGlobal = new javax.swing.JButton();
        camaraLuna = new javax.swing.JButton();
        camaraNave = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        camaraGlobal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        camaraGlobal.setText("Camara Global");
        camaraGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camaraGlobalActionPerformed(evt);
            }
        });

        camaraLuna.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        camaraLuna.setText("Camara Luna");
        camaraLuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camaraLunaActionPerformed(evt);
            }
        });

        camaraNave.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        camaraNave.setText("Camara Nave");
        camaraNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camaraNaveActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(camaraGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(camaraLuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(camaraNave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(camaraGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camaraLuna, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camaraNave, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void camaraGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camaraGlobalActionPerformed
        // TODO add your handling code here:
        universe.activarCamaraPerspectiva();
    }//GEN-LAST:event_camaraGlobalActionPerformed

    private void camaraLunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camaraLunaActionPerformed
        // TODO add your handling code here:
        universe.activarCamaraLuna();
    }//GEN-LAST:event_camaraLunaActionPerformed

    private void camaraNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camaraNaveActionPerformed
        // TODO add your handling code here:
        universe.activarCamaraNave();
    }//GEN-LAST:event_camaraNaveActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        closeApp(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    
     public void showWindow () {
        setVisible(true);
    }

    void closeApp (int code) {
        universe.closeApp(code);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton camaraGlobal;
    private javax.swing.JButton camaraLuna;
    private javax.swing.JButton camaraNave;
    private javax.swing.JButton exitButton;
    // End of variables declaration//GEN-END:variables
}
